"""Initial setup

Revision ID: c512296bbdce
Revises: 
Create Date: 2019-10-19 12:37:59.397135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c512296bbdce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "securities",
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column(
            "location",
            sa.Enum(
                "domestic",
                "international",
                "emerging_markets",
                "blend",
                name="locationenum",
            ),
            nullable=True,
        ),
        sa.Column("quote_source", sa.String(length=100), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "distributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("symbol", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["securities.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("symbol", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["securities.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quotes")
    op.drop_table("distributions")
    op.drop_table("securities")
    # ### end Alembic commands ###
